apiVersion: v1
items:
- apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
    name: gp3
  parameters:
    fsType: ext4
    type: gp3
  provisioner: kubernetes.io/aws-ebs
  reclaimPolicy: Delete
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
